// shared/lib/query-provider.tsx
'use client'

import { QUERY_GC_TIME, QUERY_RETRY_COUNT, QUERY_STALE_TIME } from '@/shared/constant/query'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { type FC, type PropsWithChildren, useState } from 'react'

export const QueryProvider: FC<PropsWithChildren> = ({ children }) => {
    const [queryClient] = useState(
        () =>
            new QueryClient({
                defaultOptions: {
                    queries: {
                        staleTime: QUERY_STALE_TIME,
                        gcTime: QUERY_GC_TIME,
                        retry: QUERY_RETRY_COUNT,
                    },
                },
            }),
    )

    return <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
}

// apps/web/src/lib/providers/query-provider.svelte
<script lang="ts">
	import { QueryClient, QueryClientProvider } from '@tanstack/svelte-query'
	import type { Snippet } from 'svelte'

	interface Props {
		children: Snippet
	}

	let { children }: Props = $props()

	const queryClient = new QueryClient({
		defaultOptions: {
			queries: {
				staleTime: 1000 * 60 * 5,
				gcTime: 1000 * 60 * 30,
				retry: 1,
				refetchOnWindowFocus: false
			}
		}
	})
</script>

<QueryClientProvider client={queryClient}>
	{@render children()}
</QueryClientProvider>
